import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Property",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const user = true;

  return (
    <html lang="en">
      <body className={inter.className}>
        {
          user ? <Header /> : ""
        }
        
        <div className="bg-orange-50 h-auto py-5">
          {children}
        </div>

        {
          user ? <Footer /> : ""
        }

      </body>
    </html>
  );
}
